# Generated by Django 6.0.2 on 2026-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='paypal',
            new_name='card1_account',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='zelle',
            new_name='card1_name',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='card2_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='card2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
